[tiles.wall]
ch = '#'
fg = [255, 255, 255, 255]
transparent = false
walkable = false

[tiles.floor]
ch = '.'
fg = [159, 159, 159, 255]
transparent = true
walkable = true

[tiles.door]
ch = '+'
fg = [191, 151, 96, 255]
transparent = false
walkable = false
open = 'open_door'

[tiles.open_door]
ch = "'"
fg = [191, 151, 96, 255]
transparent = true
walkable = true
close = 'door'

[tiles.blackboard_v]
ch = '|'
fg = [95, 95, 95, 255]
transparent = true
walkable = true
flip = 'blackboard_h'

[rooms.loss]
weight = 0.1
[rooms.loss.tiles]
'.' = 'floor'
'#' = 'wall'
'+' = 'door'
'|' = 'blackboard_v'
'_' = 'blackboard_h'
layout = '''
#+########
#........#
#..|..||.#
#........#
#..||.|_.#
#........#
##########
'''

[rooms.classroom]
weight = 1
[rooms.classroom.tiles]
'.' = 'floor'
'#' = 'wall'
'+' = 'door'
'P' = 'desk'
'|' = 'blackboard_v'
'_' = 'blackboard_h'
[rooms.classroom.layout]
min_height = 6
min_width = 8
max_height = 20
max_width = 20
ul = '''
#+#
#._
'''
u = '''
##
__
'''
ur = '''
##
|#
'''
l = '#.P'
c = '.P'
r = '|#'
dl = '###'
d = '##'
dr = '##'