[cringe]
name = "cringe"

[[cringe.attacks]]
player = [" dab on ", ""]
monster = [" dabs on ", ""]
[[cringe.attacks]]
player = [" yeet ", ""]
monster = [" yeets ", ""]
[[cringe.attacks]]
player = [" cringe at ", ""]
monster = [" cringes at ", ""]
[[cringe.attacks]]
player = [" own ", ""]
monster = [" owns ", ""]
[[cringe.attacks]]
player = [" post at ", ""]
monster = [" posts at ", ""]
[[cringe.attacks]]
player = [" dunk on ", ""]
monster = [" dunks on ", ""]
[[cringe.attacks]]
player = [" vibe check ", ""]
monster = [" vibe checks ", ""]


[[cringe.deaths]]
player = "you loose subscriber"
monster = ["the ", " looses subscriber"]
[[cringe.deaths]]
player = "you have failed your vibe check"
monster = ["the ", " has failed their vibe check"]
[[cringe.deaths]]
player = "you have failed your vibe check"
monster = ["the ", " has failed their vibe check"]
[[cringe.deaths]]
player = "you have been owned"
monster = ["the ", " has been owned"]
[[cringe.deaths]]
player = "you have been cancelled"
monster = ["the ", " has been cancelled"]
[[cringe.deaths]]
player = "you are banned"
monster = ["the ", " is banned"]
[[cringe.deaths]]
player = "you log off"
monster = ["the ", " logs off"]
[[cringe.deaths]]
player = "you have experienced a bruh moment"
monster = ["the ", " has experienced a bruh moment"]
[[cringe.deaths]]
player = "you have been turned into a corncob"
monster = ["the ", " has been turned into a corncob"]