[interface]
width = 100
height = 45
key_delay = 25

[interface.font]
font = "curses_vector_8x12.png"
width = 8
height = 12

[player]
fov = 10
[player.tile]
ch = '@'
fg = [255, 255, 255, 255]

[map]
place_attempts = 100
width = 200
height = 200
num_monsters = 50
